import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});
/*Apply Tailwind*/


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
        
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} 
      relative xs:top-[50px] sm:top-[100px]
      md:top-[200px] 
      lg:top-[320px] left-[-5rem]
      xl:left-[-7rem]
      2xl:
          antialiased  ...`}
      >
        {children}
      </body>
    </html>
  );
}